---
upgrade_firmware: True

install_system_packages:
 - htop
 - vim
 - screen
 - fortune
 - figlet
 - cowsay
 - rpi-update
 - git
 - uptimed

python2_packages:
 - python-pip
 - python-virtualenv

install_python3: False
python3_packages:
 - python3
 - python3-pip

remove_system_packages: []
