---
- name: Restart server
  become: yes
  command: reboot
  async: 0
  poll: 0
  ignore_errors: true
    
- name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=300
    become: yes
